# Generated by Django 6.1 on 2026-08-28 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0002_alter_nodoservidor_direccion_ip_registroauditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroauditoria',
            options={'ordering': ('-fecha_evento',), 'verbose_name': 'Registro de Auditoría', 'verbose_name_plural': 'Registros de Auditoría'},
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='fecha_evento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='infraestructura.nodoservidor'),
        ),
    ]
