# Generated by Django 6.1 on 2026-09-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0003_alter_registroauditoria_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Fallo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('severidad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Severidad')),
                ('resuelto', models.BooleanField(default=False, verbose_name='¿Resuelto?')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='infraestructura.nodoservidor')),
            ],
            options={
                'verbose_name': 'Incidencia de Servidor',
                'verbose_name_plural': 'Alertas e Incidencias',
                'ordering': ('-fecha_evento',),
            },
        ),
    ]
