# Generated by Django 6.1 on 2026-09-15 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0004_incidenciaservidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoNodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarea', models.CharField(max_length=150, verbose_name='Título del Mantenimiento')),
                ('descripcion_tecnica', models.TextField(verbose_name='Descripción de la Tarea')),
                ('tipo', models.CharField(choices=[('actualizacion', 'Actualización de Sistema'), ('backup', 'Respaldo de Base de Datos'), ('seguridad', 'Parche de Seguridad'), ('hardware', 'Revisión de Hardware')], default='actualizacion', max_length=30, verbose_name='Tipo de Tarea')),
                ('completado', models.BooleanField(default=False, verbose_name='¿Tarea Ejecutada?')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha y Hora Programada')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='infraestructura.nodoservidor', verbose_name='Servidor Asignado')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Servidor',
                'verbose_name_plural': 'Programación de Mantenimientos',
            },
        ),
    ]
